// packages/cli/bench/scan/blind/vue-app/src/views/Settings.vue
<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Input } from "@/components/ui/input";
import { Button as UiButton } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import type { AlertVariants } from "@/components/ui/alert";

const form = reactive({ name: "", email: "", website: "" });
const saving = ref(false);
const variant = ref<"line" | "segmented">("line");
const status = ref<{ kind: "ok" | "error"; message: string; tone?: AlertVariants["intent"] } | null>(null);
const accent = "#7c3aed";
const buttonAttrs = { type: "submit", form: "profile" } as const;
const fieldClass = computed(() => (status.value?.kind === "error" ? "border-destructive" : ""));

async function save(): Promise<void> {
  saving.value = true;
  await new Promise<void>((r) => setTimeout(r, 300));
  saving.value = false;
  status.value = { kind: "ok", message: "Saved" };
}
</script>

<template>
  <Tabs default-value="profile" :variant class="w-full max-w-2xl">
    <TabsList :class="[variant === 'line' && 'bg-transparent', 'w-full']">
      <TabsTrigger value="profile">Profile</TabsTrigger>
      <TabsTrigger value="danger" class="data-[state=active]:text-destructive">Danger zone</TabsTrigger>
    </TabsList>
    <TabsContent value="profile" class="space-y-4 pt-4">
      <Alert v-if="status" :intent="status.kind === 'ok' ? 'success' : 'danger'" v-bind:variant="'soft'">
        <AlertTitle>{{ status.message }}</AlertTitle>
      </Alert>
      <form id="profile" class="space-y-3" @submit.prevent="save">
        <Input v-model="form.name" placeholder="Name" />
        <Input v-model="form.email" type="email" :class="fieldClass" size="lg" />
        <Input
          v-model="form.website"
          :size="'sm'"
          :style="{ borderColor: accent, width: '100%' }"
        />
        <UiButton v-bind="buttonAttrs" :disabled="saving" class="min-w-[120px] h-[38px]">
          {{ saving ? "Saving…" : "Save" }}
        </UiButton>
      </form>
    </TabsContent>
    <TabsContent value="danger">
      <Alert intent="danger" class="rounded-[6px] border-2 p-[13px]">
        <AlertTitle class="!font-bold">Delete workspace</AlertTitle>
        <AlertDescription>This removes every project and invoice.</AlertDescription>
      </Alert>
      <Dialog>
        <DialogTrigger as-child>
          <UiButton intent="danger" variant="outline" class="mt-4">Delete…</UiButton>
        </DialogTrigger>
        <DialogContent class="sm:max-w-[425px]" style="padding: 32px">
          <DialogHeader>
            <DialogTitle class="text-destructive">Are you sure?</DialogTitle>
          </DialogHeader>
          <DialogFooter class="gap-2 sm:gap-0">
            <UiButton variant="ghost">Cancel</UiButton>
            <UiButton intent="danger" class="bg-red-700 hover:bg-red-800">Delete</UiButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </TabsContent>
  </Tabs>
</template>

// packages/cli/bench/scan/blind/svelte-app/src/routes/settings/+page.svelte
<script lang="ts">
  import * as Tabs from "$lib/components/ui/tabs/index.js";
  import * as Alert from "$lib/components/ui/alert/index.js";
  import * as Dialog from "$lib/components/ui/dialog/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import { Button } from "$lib/components/ui/button/index.js";
  import { Root as CardRoot, Content as CardContent } from "$lib/components/ui/card/index.js";
  import SubmitButton from "$lib/components/SubmitButton.svelte";
  import MemberList from "$lib/components/MemberList.svelte";

  let { data }: { data: { cardClass: string; members: Array<{ id: string; name: string; role: string }> } } = $props();
  let name = $state("");
  let email = $state("");
  let confirmOpen = $state(false);
  let saved = $state<boolean | null>(null);
  let tab = $state("profile");
  let fieldSize = $state<"sm" | "md">("md");
  const accent = "#dc2626";
</script>

<Tabs.Root bind:value={tab} variant="segmented" class="space-y-6">
  <Tabs.List class="w-full md:w-auto">
    <Tabs.Trigger value="profile">Profile</Tabs.Trigger>
    <Tabs.Trigger value="team" class="data-[state=active]:bg-white! data-[state=active]:shadow-sm">Team</Tabs.Trigger>
    <Tabs.Trigger value="danger">Danger</Tabs.Trigger>
  </Tabs.List>

  <Tabs.Content value="profile">
    {#if saved === true}
      <Alert.Root intent="success">
        <Alert.Title>Saved</Alert.Title>
      </Alert.Root>
    {:else if saved === false}
      <Alert.Root intent="danger" variant="soft" style="border-color: {accent}; margin-bottom: 1rem">
        <Alert.Title class="font-semibold">Could not save</Alert.Title>
        <Alert.Description>Check the highlighted fields.</Alert.Description>
      </Alert.Root>
    {/if}
    <CardRoot class="mt-4 {data.cardClass}">
      <CardContent class="grid gap-4 p-6">
        <label class="grid gap-1.5 text-sm">
          Name
          <Input bind:value={name} size={fieldSize} class="h-11" />
        </label>
        <label class="grid gap-1.5 text-sm">
          Email
          <Input type="email" bind:value={email} class={{ "border-destructive": email.length > 0 && !email.includes("@"), "w-full": true }} />
        </label>
        <SubmitButton pending={false}>Save</SubmitButton>
      </CardContent>
    </CardRoot>
  </Tabs.Content>

  <Tabs.Content value="team">
    <MemberList items={data.members}>
      {#snippet actions(member)}
        <Button variant="ghost" size="xs" onclick={() => console.log(member.id)} class="h-7 px-2">Manage</Button>
      {/snippet}
    </MemberList>
  </Tabs.Content>

  <Tabs.Content value="danger">
    <Dialog.Root bind:open={confirmOpen}>
      <Dialog.Trigger>
        {#snippet child({ props })}
          <Button {...props} intent="danger" variant="outline">Delete workspace</Button>
        {/snippet}
      </Dialog.Trigger>
      <Dialog.Content class="sm:max-w-md rounded-[4px]">
        <Dialog.Header>
          <Dialog.Title>Delete workspace?</Dialog.Title>
        </Dialog.Header>
        <Dialog.Footer class="gap-2">
          <Button variant="ghost" onclick={() => (confirmOpen = false)}>Cancel</Button>
          <Button intent="danger" class="h-[42px] px-[18px]" onclick={() => (confirmOpen = false)}>Delete</Button>
        </Dialog.Footer>
      </Dialog.Content>
    </Dialog.Root>
  </Tabs.Content>
</Tabs.Root>
