// packages/cli/bench/scan/blind/svelte-app/src/routes/billing/+page.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button";
  import { Badge } from "$lib/components/ui/badge";
  import * as Alert from "$lib/components/ui/alert";
  import * as Card from "$lib/components/ui/card";
  import { Input } from "$lib/components/ui/input";
  import type { PageData } from "./$types";

  export let data: PageData;

  let coupon = "";
  let applying = false;
  $: overdue = data.invoices.filter((i) => i.status === "overdue");
  $: total = data.invoices.reduce((sum, i) => sum + i.amount, 0);
  const statusIntent = { paid: "success", open: "info", overdue: "danger" } as const;

  async function apply() {
    applying = true;
    await fetch("?/coupon", { method: "POST", body: JSON.stringify({ coupon }) });
    applying = false;
  }
</script>

{#if overdue.length > 0}
  <Alert.Root intent="warning" class="mb-6 border-amber-300 bg-amber-50 dark:bg-amber-950">
    <Alert.Title>{overdue.length} overdue {overdue.length === 1 ? "invoice" : "invoices"}</Alert.Title>
  </Alert.Root>
{/if}

<Card.Root class="overflow-hidden">
  <Card.Header class="border-b bg-muted/40">
    <Card.Title>Invoices</Card.Title>
  </Card.Header>
  <Card.Content class="p-0">
    <table class="w-full text-sm">
      <tbody>
        {#each data.invoices as inv (inv.id)}
          <tr class="border-b last:border-0" class:opacity-50={inv.status === "paid"}>
            <td class="px-4 py-2">{inv.number}</td>
            <td class="px-4 py-2">
              <Badge intent={statusIntent[inv.status]} variant="soft" class="font-mono">{inv.status}</Badge>
            </td>
            <td class="px-4 py-2 text-right">{(inv.amount / 100).toFixed(2)}</td>
            <td class="px-4 py-2">
              <Button variant="link" size="xs" href="/billing/{inv.id}.pdf" class="h-auto p-0">PDF</Button>
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </Card.Content>
  <Card.Footer class="gap-3 border-t pt-4">
    <Input bind:value={coupon} placeholder="Coupon code" size="sm" class="w-40 uppercase" />
    <Button size="sm" variant="outline" on:click={apply} disabled={applying || coupon.length < 4} class="h-8 px-3 font-semibold">Apply</Button>
    <span class="ml-auto font-medium">Total {(total / 100).toFixed(2)}</span>
  </Card.Footer>
</Card.Root>

<Button variant="ghost" intent="neutral" style="width: 100%; margin-top: 1.5rem" on:click={() => history.back()}>Back</Button>

// packages/cli/bench/scan/blind/react-app/src/pages/Billing.tsx
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge as StatusPill } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import styles from "./Billing.module.css";
import type { Invoice } from "@/types";

const tone = { paid: "success", open: "warning", void: "neutral" } as const;
const copy = "Click <Button intent=\"danger\">Cancel plan</Button> to stop billing.";

/**
 * Billing page.
 * @example
 *   <Billing invoices={[]} onCancel={() => {}} />
 *   // renders <Button intent="danger" className="rounded-none"> in the footer
 */
export function Billing({ invoices, onCancel }: { invoices: Invoice[]; onCancel: () => Promise<void> }) {
  const [confirming, setConfirming] = useState(false);
  const [sort, setSort] = useState<keyof Invoice>("id");
  const rows = [...invoices].sort((a, b) => (a[sort] < b[sort] ? -1 : 1));
  const pastDue = rows.some((r) => r.status === "open");

  return (
    <section className="space-y-6" title={copy}>
      {pastDue && (
        <Alert intent="warning" variant="soft" className="rounded-[6px] border-l-4 border-amber-500">
          <AlertTitle>Payment past due</AlertTitle>
          <AlertDescription className="text-[13px] leading-5">
            Update your card to keep your plan.
          </AlertDescription>
        </Alert>
      )}
      <table className={styles.table}>
        <tbody>
          {rows.map((inv) => (
            <tr key={inv.id}>
              <td>{inv.id}</td>
              <td>
                <StatusPill intent={tone[inv.status]} className={styles.pill}>
                  {inv.status}
                </StatusPill>
              </td>
              <td className="text-right">
                <Button variant="link" size="sm" onClick={() => setSort("amount")} className="h-auto p-0 text-[#1a1a1a]">
                  ${(inv.amount / 100).toFixed(2)}
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <Dialog open={confirming} onOpenChange={setConfirming}>
        <DialogTrigger asChild>
          <Button
            variant="outline"
            intent="danger"
            onClick={() => {
              if (rows.length > 0) setConfirming(true);
            }}
            className={cn("w-full sm:w-auto", {
              "border-2": pastDue,
            })}
          >
            Cancel plan
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-md p-0 overflow-hidden">
          <DialogHeader className="px-6 pt-6">
            <DialogTitle>Cancel your plan?</DialogTitle>
          </DialogHeader>
          <DialogFooter className="bg-muted/50 px-6 py-4">
            <Button variant="ghost" onClick={() => setConfirming(false)}>
              Keep plan
            </Button>
            <Button
              intent="danger"
              onClick={async () => {
                await onCancel();
                setConfirming(false);
              }}
            >
              Yes, cancel
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </section>
  );
}
