// packages/cli/bench/scan/blind/vue-app/src/views/Billing.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertTitle } from "@/components/ui/alert";

type Invoice = { id: string; total: number; status: "paid" | "due" | "failed" };

const invoices = ref<Invoice[]>([]);
const failed = computed(() => invoices.value.filter((i) => i.status === "failed"));
const intentFor: Record<Invoice["status"], "success" | "warning" | "danger"> = { paid: "success", due: "warning", failed: "danger" };
const upgrading = ref(false);
</script>

<template>
  <div class="space-y-6">
    <Alert v-if="failed.length > 0" intent="danger" variant="soft">
      <AlertTitle>{{ failed.length }} payment{{ failed.length > 1 ? "s" : "" }} failed</AlertTitle>
      <Button intent="danger" size="sm" class="tracking-wide hover:bg-red-800">Retry all</Button>
    </Alert>
    <Card>
      <CardHeader>
        <CardTitle>Invoices</CardTitle>
      </CardHeader>
      <CardContent class="p-0">
        <table class="w-full text-sm">
          <tr v-for="inv in invoices" :key="inv.id" class="border-b last:border-0">
            <td class="p-3">{{ inv.id }}</td>
            <td class="p-3">
              <Badge :intent="intentFor[inv.status]" variant="soft">{{ inv.status }}</Badge>
            </td>
            <td class="p-3 text-right">
              <Button variant="ghost" size="xs" :class="['tracking-wide', inv.status === 'failed' ? 'text-destructive' : '']">
                Download
              </Button>
            </td>
          </tr>
        </table>
      </CardContent>
      <CardFooter class="border-t pt-4">
        <Button
          :variant="upgrading ? 'solid' : 'outline'"
          :class="{ 'tracking-wide': true, 'bg-red-800': upgrading }"
          @click="() => { upgrading = !upgrading }"
        >
          {{ upgrading ? "Confirm upgrade" : "Upgrade plan" }}
        </Button>
      </CardFooter>
    </Card>
  </div>
</template>

// packages/cli/bench/scan/blind/react-app/src/pages/Billing.tsx
import { useState } from "react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge as StatusPill } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";
import styles from "./Billing.module.css";
import type { Invoice } from "@/types";

const tone = { paid: "success", open: "warning", void: "neutral" } as const;
const copy = "Click <Button intent=\"danger\">Cancel plan</Button> to stop billing.";

/**
 * Billing page.
 * @example
 *   <Billing invoices={[]} onCancel={() => {}} />
 *   // renders <Button intent="danger" className="rounded-none"> in the footer
 */
export function Billing({ invoices, onCancel }: { invoices: Invoice[]; onCancel: () => Promise<void> }) {
  const [confirming, setConfirming] = useState(false);
  const [sort, setSort] = useState<keyof Invoice>("id");
  const rows = [...invoices].sort((a, b) => (a[sort] < b[sort] ? -1 : 1));
  const pastDue = rows.some((r) => r.status === "open");

  return (
    <section className="space-y-6" title={copy}>
      {pastDue && (
        <Alert intent="warning" variant="soft" className="rounded-[6px] border-l-4 border-amber-500">
          <AlertTitle>Payment past due</AlertTitle>
          <AlertDescription className="text-[13px] leading-5">
            Update your card to keep your plan.
          </AlertDescription>
        </Alert>
      )}
      <table className={styles.table}>
        <tbody>
          {rows.map((inv) => (
            <tr key={inv.id}>
              <td>{inv.id}</td>
              <td>
                <StatusPill intent={tone[inv.status]} className={styles.pill}>
                  {inv.status}
                </StatusPill>
              </td>
              <td className="text-right">
                <Button variant="link" size="sm" onClick={() => setSort("amount")} className="h-auto p-0 text-[#1a1a1a]">
                  ${(inv.amount / 100).toFixed(2)}
                </Button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <Dialog open={confirming} onOpenChange={setConfirming}>
        <DialogTrigger asChild>
          <Button
            variant="outline"
            intent="danger"
            onClick={() => {
              if (rows.length > 0) setConfirming(true);
            }}
            className={cn("w-full sm:w-auto", {
              "border-2": pastDue,
            })}
          >
            Cancel plan
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-md p-0 overflow-hidden">
          <DialogHeader className="px-6 pt-6">
            <DialogTitle>Cancel your plan?</DialogTitle>
          </DialogHeader>
          <DialogFooter className="bg-muted/50 px-6 py-4">
            <Button variant="ghost" onClick={() => setConfirming(false)}>
              Keep plan
            </Button>
            <Button
              intent="danger"
              onClick={async () => {
                await onCancel();
                setConfirming(false);
              }}
            >
              Yes, cancel
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </section>
  );
}
