// packages/cli/bench/import/holdout2/k1-daisyui-v5/src/components/InvoiceCard.tsx
type Props = {
  id: string;
  customer: string;
  amount: number;
  status: "paid" | "due" | "overdue";
};

const badge: Record<Props["status"], string> = {
  paid: "badge-success",
  due: "badge-warning",
  overdue: "badge-error",
};

export function InvoiceCard({ id, customer, amount, status }: Props) {
  return (
    <article className="card border border-base-300 bg-base-100">
      <div className="card-body gap-3">
        <div className="flex items-center justify-between">
          <span className="font-mono text-xs text-base-content/60">{id}</span>
          <span className={`badge badge-soft ${badge[status]}`}>{status}</span>
        </div>
        <h2 className="card-title">{customer}</h2>
        <p className="text-3xl font-semibold tabular-nums">
          {amount.toLocaleString("en-US", { style: "currency", currency: "USD" })}
        </p>
        {status === "overdue" && (
          <div role="alert" className="alert alert-error alert-soft text-sm">
            Payment is 14 days late.
          </div>
        )}
        <div className="card-actions justify-end">
          <button className="btn btn-ghost btn-sm">View</button>
          <button className="btn btn-primary btn-sm">Send reminder</button>
        </div>
      </div>
    </article>
  );
}

// packages/cli/bench/import/holdout/h3-vuetify-3/src/components/InvoiceCard.vue
<template>
  <v-card border flat>
    <v-card-item>
      <v-card-title>{{ invoice.customer }}</v-card-title>
      <v-card-subtitle>{{ invoice.id }}</v-card-subtitle>
      <template #append>
        <v-chip :color="statusColor" size="small" label>{{ invoice.status }}</v-chip>
      </template>
    </v-card-item>
    <v-divider />
    <v-card-text class="d-flex justify-space-between align-center">
      <span class="text-h6">{{ amount }}</span>
      <span class="text-body-2 text-medium-emphasis">Net 30</span>
    </v-card-text>
    <v-card-actions>
      <v-btn color="primary" variant="flat">Send reminder</v-btn>
      <v-btn variant="text">View</v-btn>
    </v-card-actions>
  </v-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'

export type Invoice = { id: string; customer: string; amount: number; status: 'paid' | 'open' | 'overdue' }

const props = defineProps<{ invoice: Invoice }>()

const statusColor = computed(() =>
  props.invoice.status === 'paid' ? 'success' : props.invoice.status === 'overdue' ? 'error' : 'warning',
)

const amount = computed(() =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(props.invoice.amount),
)
</script>
